<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
/** @var \Magento\Contact\Block\ContactForm $block */
?>

<div class="contact-wrapper">

    <div class="contact-inner-container">

        <div class="contact-content">
           <h1><span>information</span></h1>

           <div class="info">
               <ul>
                   <li>
                        <span class="build"></span>
                        <div class="content">
                            <h4>address:</h4>
                            <span>sunset av, 12345, berlin</span>
                        </div>
                   </li>
                   <li>
                        <span class="phone"></span>
                        <div class="content">
                            <h4>phone:</h4>
                            <span>01234 / 141-4215</span>
                        </div>
                   </li>
                   <li>
                        <span class="mail"></span>
                        <div class="content">
                            <h4>e-mail:</h4>
                            <span>info@example.com</span>
                        </div>
                   </li>
               </ul>
           </div>

        </div>

        <div class="contact-content">
           <h1><span>business hours</span></h1>

           <div class="info">
               <h6>monday - friday: <span>10am - 8pm</span></h6>
           </div>
           
        </div>

        
    </div>

    <div class="form-container">
        <form class="form contact"
            action="<?= $block->escapeUrl($block->getFormAction()) ?>"
            id="contact-form"
            method="post"
            data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
            data-mage-init='{"validation":{}}'>
            <fieldset class="fieldset">
                <div class="field name required">
                    <label class="label" for="name"><span><?= $block->escapeHtml(__('Name')) ?></span></label>
                    <div class="control">
                        <input name="name" id="name" title="<?= $block->escapeHtmlAttr(__('Name')) ?>" value="<?= $block->escapeHtmlAttr($this->helper('Magento\Contact\Helper\Data')->getPostValue('name') ?: $this->helper('Magento\Contact\Helper\Data')->getUserName()) ?>" class="input-text" type="text" data-validate="{required:true}"/>
                    </div>
                </div>
                <div class="field email required">
                    <label class="label" for="email"><span><?= $block->escapeHtml(__('Email')) ?></span></label>
                    <div class="control">
                        <input name="email" id="email" title="<?= $block->escapeHtmlAttr(__('Email')) ?>" value="<?= $block->escapeHtmlAttr($this->helper('Magento\Contact\Helper\Data')->getPostValue('email') ?: $this->helper('Magento\Contact\Helper\Data')->getUserEmail()) ?>" class="input-text" type="email" data-validate="{required:true, 'validate-email':true}"/>
                    </div>
                </div>
                <!-- <div class="field telephone">
                    <label class="label" for="telephone"><span><?= $block->escapeHtml(__('Phone Number')) ?></span></label>
                    <div class="control">
                        <input name="telephone" id="telephone" title="<?= $block->escapeHtmlAttr(__('Phone Number')) ?>" value="<?= $block->escapeHtmlAttr($this->helper('Magento\Contact\Helper\Data')->getPostValue('telephone')) ?>" class="input-text" type="text" />
                    </div>
                </div> -->
                <div class="field comment required">
                    <label class="label" for="comment"><span><?= $block->escapeHtml(__('Message')) ?></span></label>
                    <div class="control">
                        <textarea name="comment" id="comment" title="<?= $block->escapeHtmlAttr(__('What’s on your mind?')) ?>" class="input-text" cols="5" rows="3" data-validate="{required:true}"><?= $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getPostValue('comment')) ?></textarea>
                    </div>
                </div>
                <?= $block->getChildHtml('form.additional.info') ?>
            </fieldset>
            <div class="actions-toolbar">
                <div class="primary">
                    <input type="hidden" name="hideit" id="hideit" value="" />
                    <button type="submit" title="<?= $block->escapeHtmlAttr(__('Submit')) ?>" class="action submit primary">
                        <span><?= $block->escapeHtml(__('Submit')) ?></span>
                    </button>
                </div>
            </div>
        </form>
    </div>

    <?php
    echo $this->getLayout()
    ->createBlock('Magento\Cms\Block\Block')
    ->setBlockId('social-links')
    ->toHtml();
    ?>

</div>


<div class="map">

    <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d13482.730780759026!2d-96.646186!3d32.3472269!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x76b2774fcf39af40!2sParty%20Club%20of%20America!5e0!3m2!1sen!2sin!4v1568901749475!5m2!1sen!2sin" width="100%" height="600" frameborder="0" style="border:0;" allowfullscreen=""></iframe>

</div>